version: '3.4'

services:
  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq
    hostname: "messageBroker"
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 5s
      timeout: 15s
      retries: 3
    networks:
      - services-network
    ports:
      - "5672:5672"
      - "15672:15672"

  backgroundworker:
    image: ${DOCKER_REGISTRY-}backgroundworker
    hostname: backgroundworker
    container_name: backgroundworker
    restart: on-failure
    networks:
      - services-network
    build:
      context: .
      dockerfile: BackgroundWorker/Dockerfile
    depends_on:
      rabbitmq:
        condition: service_healthy
    ports:
      - "60001:80"
      - "60002:443"

  demoapi:
    image: ${DOCKER_REGISTRY-}demoapi
    container_name: demoapi
    hostname: demoapi
    restart: on-failure
    networks:
      - services-network
    build:
      context: .
      dockerfile: DemoApi/Dockerfile
    depends_on:
      rabbitmq:
        condition: service_healthy
    ports:
      - "60003:80"
      - "60004:443"

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sql_server2022
    environment:
      ACCEPT_EULA: Y
      MSSQL_SA_PASSWORD: P@ssword
    networks:
      - services-network
    ports:
      - "1433:1433"
    depends_on:
      - rabbitmq

networks:
  services-network: 


